### ISSUE TITLE
maillog configuration?

### ISSUE THREAD

**Issue by Szparki** [voxpupuli/puppet-postfix#386] opened 2024-04-25 11:53 UTC
The module is not managing _log_ related settings, such as `maillog_file` or `maillog_file_rotate_suffix`.
Without these on Ubuntu and Debian, postfix logs are filling up `/var/log/syslog`, making it difficult to find none mail related information.

## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: puppet-postfix (v4.4.0)

**Comment by smortex** [comment] 2024-04-26 17:49
Correct.  For historic reasons, some parameters must be passed to the `postfix` class and are then passed to `postfix::config` resources, but rather than adding more like this, I feel it is better to directly write the config you wants with `postfix::config` resources.

Closing since the issue is resolved.

**Closed by smortex** 2024-04-26 17:49 UTC

**Comment by Szparki** [comment] 2024-04-29 08:53
I see, thank you @smortex !
Do you have an example how to define them in hieradata?

Also I noticed that I do need `postlog` in `master.cf` but I haven't found an option to configure it with the module. If I add by hand it gets removed:

```
Apr 26 14:04:01 postfix-server postfix/postfix-script[1877795]: fatal: missing 'postlog' service in master.cf - run 'postfix upgrade-configuration'
```
```
Notice: /Stage[main]/Postfix::Files/File[/etc/postfix/master.cf]/content:
--- /etc/postfix/master.cf	2024-04-29 08:47:01.814602062 +0000
+++ /tmp/puppet-file20240429-1989427-r6yung	2024-04-29 08:47:16.946726595 +0000
@@ -44,7 +44,6 @@
 lmtp      unix  -       -       n       -       -       lmtp
 anvil     unix  -       -       n       -       1       anvil
 scache    unix  -       -       n       -       1       scache
-postlog   unix-dgram n  -       n       -       1       postlogd
 #
 # ====================================================================
 # Interfaces to non-Postfix software. Be sure to examine the manual
 ```

**Comment by Szparki** [comment] 2024-04-29 11:24
I can use [master_entries](https://github.com/voxpupuli/puppet-postfix/blob/master/REFERENCE.md#-postfix--master_entries) to add the postlog line, good
